FROM ubuntu:24.04

RUN apt-get update && apt-get install -y \
  wget \
  curl \
  git \
  ffmpeg \
  build-essential \
  libssl-dev \
  zlib1g-dev \
  libbz2-dev \
  libreadline-dev \
  libsqlite3-dev \
  llvm \
  libncursesw5-dev \
  xz-utils \
  tk-dev \
  libxml2-dev \
  libxmlsec1-dev \
  libffi-dev \
  liblzma-dev

WORKDIR /root

SHELL ["/bin/bash", "-c"]

RUN curl https://pyenv.run | bash

ENV PYENV_ROOT="/root/.pyenv"

ENV PATH="$PYENV_ROOT/bin:$PATH"

RUN eval "$(pyenv init -)"

RUN eval "$(pyenv virtualenv-init -)"

RUN echo 'PYENV_ROOT="/root/.pyenv"' >> /root/.bashrc
RUN echo '[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"'  >> /root/.bashrc
RUN echo 'eval "$(pyenv init -)"' >> /root/.bashrc
RUN echo 'eval "$(pyenv virtualenv-init -)"' >> /root/.bashrc

RUN echo 'PYENV_ROOT="/root/.pyenv"' >> /root/.profile
RUN echo '[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"'  >> /root/.profile
RUN echo 'eval "$(pyenv init -)"' >> /root/.profile
RUN echo 'eval "$(pyenv virtualenv-init -)"' >> /root/.profile

RUN source /root/.bashrc

# 3.11.8 / 3.10.14

RUN pyenv install 3.10.14

RUN pyenv global 3.10.14

RUN apt-get install -y libasound2-dev libgtk2.0-dev libx11-dev

RUN ln -s /root/.pyenv/shims/python /usr/bin/python

RUN mv /usr/bin/python3 /usr/bin/python3.original

RUN ln -s /root/.pyenv/shims/python3 /usr/bin/python3

RUN bash -i -c "source ~/.bashrc && pyenv virtualenv 3.10.14 vdub-applio"

RUN bash -i -c "source ~/.bashrc && pyenv activate vdub-applio"

RUN bash -i -c "source ~/.bashrc && pip install --upgrade pip"

# RUN python -m ensurepip --upgrade

# RUN apt-get install -y pip

# RUN pip install torch torchvision torchaudio praat-parselmouth
RUN bash -i -c "source ~/.bashrc && pip install torch torchvision"

# RUN bash -i -c "source ~/.bashrc && pip install prophet"

# RUN bash -i -c "source ~/.bashrc && pip install praat-parselmouth"

RUN bash -i -c "source ~/.bashrc && pip install git+https://github.com/YannickJadoul/Parselmouth"

RUN git clone https://github.com/IAHispano/Applio.git

WORKDIR /root/Applio

# RUN chmod +x run-install.sh

RUN bash -i -c "source ~/.bashrc && python -m venv .venv"

RUN bash -i -c "source ~/.bashrc && . .venv/bin/activate"

RUN bash -i -c "source ~/.bashrc && python -m ensurepip"

# TODO: Replace 'praat-parselmouth' in requirements.txt with praat-parselmouth @ git+https://github.com/YannickJadoul/Parselmouth
RUN sed -i 's/praat-parselmouth/praat-parselmouth @ git\+https:\/\/github.com\/YannickJadoul\/Parselmouth/g' requirements.txt

RUN bash -i -c "source ~/.bashrc && python -m pip install -r requirements.txt"

# RUN bash -i -c "source ~/.bashrc && ./run-install.sh"

# RUN chmod +x run-applio.sh

# RUN ./run-applio.sh

ENV PYTORCH_ENABLE_MPS_FALLBACK=1

ENV PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0

RUN apt-get install -y vim sox

RUN bash -i -c "source ~/.bashrc && python -m pip install edge-tts"

EXPOSE 6969

ENV GRADIO_SERVER_NAME="0.0.0.0"

WORKDIR /root

RUN mkdir shared

WORKDIR /root/Applio

# RUN bash -i -c "source ~/.bashrc && python app.py"

# WORKDIR /root

# CMD python app.py --open --share True
